<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-admin.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'active_widgets_explanation' => 'Các công cụ đang hoạt động:',
		'add_category_button' => 'Thêm chủ đề',
		'add_field_button' => 'Thêm trường',
		'add_link_button' => 'Thêm Link',
		'add_link_link' => ' - ^1thêm link^2',
		'add_new_field' => 'Thêm trường mới',
		'add_new_title' => 'Thêm chức danh',
		'add_page_button' => 'Thêm trang',
		'add_title_button' => 'Thêm tiêu đề',
		'add_widget_button' => 'Thêm công cụ',
		'add_widget_link' => ' - ^1thêm công cụ ^2',
		'admin_title' => 'Quản trị',
		'after_footer' => 'Sau đó liên kết ở cuối trang',
		'after_main_menu' => 'Sau đó tab ở đầu',
		'after_x_tab' => 'Sau đó "^" tab',
		'after_x' => 'Sau đó "^"',
		'moderate_title' => 'Duyệt bài',
		'basic_editor' => 'Trình soạn thảo Căn bản',
		'before_main_menu' => 'Trước khi tab ở đầu',
		'blobs_directory_error' => 'Các thư mục ^ định nghĩa như QA_BLOBS_DIRECTORY không có khả năng viết bởi webserver.',
		'blobs_move_complete' => 'Di chuyển các hình ảnh và các tài liệu được tải lên hoàn thành.',
		'blobs_move_moved' => 'Di chuyển ^1 của ^2 các hình ảnh và các tài liệu được tải lên',
		'blobs_stop' => 'Ngừng di chuyển',
		'blobs_to_db' => 'Di chuyển đến cơ sở dữ liệu',
		'blobs_to_db_note' => '- di chuyển tất cả các hình ảnh và các tài liệu được tải lên từ đĩa đến cơ sở dữ liệu',
		'blobs_to_disk' => 'Di chuyển đến bộ nhớ ngoài',
		'blobs_to_disk_note' => '- di chuyển tất cả các hình ảnh và các tài liệu được tải lên từ cơ sở dữ liệu lên đĩa',
		'block_button' => 'khóa',
		'block_ips_note' => 'Sử dụng dấu gạch ngang cho các miền hoặc dấu * để nối với bất kỳ số nào đó. Ví dụ: 192.168.0.4 , 192.168.0.0-192.168.0.31 , 192.168.0.*',
		'block_words_note' => 'Sử dụng một dấu * để nối với từ bất kỳ. Ví dụ: doh (will only match exact word doh) , doh* (will match doh or dohno) , do*h (will match doh, dooh, dough).',
		'cancel_mailing_button' => 'Hủy bỏ gửi mail',
		'categories_introduction' => 'Để bắt đầu với một chủ đề, Bấm vào button\'Thêm Chủ đề\'.',
		'categories_not_shown' => 'Một vài câu hỏi có chủ đề sẽ không được hiển thị.',
		'categories_title' => 'Chủ đề',
		'categories' => 'Chủ đề',
		'category_add_sub' => 'thêm chủ đề con',
		'category_added' => 'Chủ đề được thêm',
		'category_already_used' => 'Cái này đang được sử dụng bởi một chủ đề nào đó',
		'category_default_slug' => 'chủ đề-^',
		'category_description' => 'Tùy chọn mô tả chủ đề:',
		'category_max_depth_x' => 'Một vài tùy chọn có lẽ được được ẩn để tránh một chủ đề đi sâu hơn ^ mức độ.',
		'category_move_parent' => 'di chuyển đến một nhánh chính khác',
		'category_name_first' => 'Tên của chủ đề đầu tiên:',
		'category_name' => 'Tên chủ đề:',
		'category_no_add_subs_x' => 'Chủ đề này không thể có chủ đề con, bởi vì nó đang được chạy ^ dưới mức độ.',
		'category_no_delete_subs' => 'Chủ đề này không thể xóa được bởi vì nó còn có một chủ đề con.',
		'category_no_sub_error' => '^q câu hỏi trong chủ đề này không có chủ đề con - ^1tập chủ đề con^2',
		'category_no_sub_to' => 'Di chuyển các câu hỏi trong ^ không có chủ đề con đến:',
		'category_no_subs' => 'Trống',
		'category_none_error' => '^q câu hỏi hiện tại không có chủ đề con - ^1tập chủ đề^2',
		'category_none_to' => 'Di chuyển các câu hỏi không có chủ đề đến:',
		'category_parent' => 'Chủ đề chính:',
		'category_saved' => 'Chủ đề đã được lưu',
		'category_slug' => 'Category slug - URL fragment:',
		'category_subs' => 'Chủ đề:',
		'category_top_level' => 'Không có chủ đề chính (mức độ đầu tiên)',
		'characters' => 'ký tự',
		'check_language_suffix' => ' - ^1kiểm tra các file ngôn ngữ^2',
		'click_name_edit' => 'Chỉnh sửa trang hoặc link:',
		'database_cleanup' => 'Các hoạt động làm mới cơ sở dữ liệu',
		'delete_category_reassign' => 'Xóa chủ đề này và phân loại lại câu hỏi của mình',
		'delete_category' => 'Xóa chủ đề này',
		'delete_field' => 'Xóa trường này',
		'delete_hidden_complete' => 'Ẩn tất các bài đăng mà không phụ thuộc đã bị xóa',
		'delete_hidden_note' => ' - ẩn tất cả các câu hỏi, câu trả lời và bình luận mà không phụ thuộc',
		'delete_hidden' => 'Xóa các bài đăng ẩn',
		'delete_link' => 'Xóa link này',
		'delete_page' => 'Xóa trang này',
		'delete_stop' => 'Ngừng việc xóa',
		'delete_title' => 'Xóa tiêu đề này',
		'delete_widget_position' => 'Xóa công cụ này từ vị trí này',
		'edit_custom_page' => 'Cập nhật chỉnh sủa trang',
		'edit_field' => ' - ^1cập nhật^2',
		'edit_link' => ' - ^1cập nhật link^2',
		'edit_page' => ' - ^1cập nhật trang^2',
		'edit_title' => ' - ^1cập nhật tiêu đề^2',
		'emails_per_minute' => 'Các thư điện tử mỗi phút',
		'emails_title' => 'Thư điện tử',
		'feed_link_example' => 'Ví dụ feed',
		'feed_link' => 'Feed',
		'feeds_title' => 'RSS',
		'field_link_url' => 'Liên kết ngoài',
		'field_multi_line' => 'Nhiều dòng văn bản',
		'field_name' => 'Tên trường:',
		'field_single_line' => 'Dòng văn bản duy nhất',
		'field_type' => 'Loại nội dung:',
		'first' => 'Đầu tiên',
		'flagged_title' => 'Các phản ánh',
		'form_security_expired' => 'Mẫu mã bảo vệ hết hiệu lực - vui lòng thử lại',
		'from_anon' => 'Từ vô danh:',
		'from_users' => 'Từ các thành viên:',
		'general_title' => 'Tổng quan',
		'hidden_answers_deleted' => 'Đã xóa ^1 của ^2 các câu trả lời ẩn mà không phụ thuộc...',
		'hidden_comments_deleted' => 'Đã xóa ^1 của ^2 các bình luận ẩn...',
		'hidden_questions_deleted' => 'Đã xóa ^1 của ^2 các câu hỏi ẩn mà không phụ thuộc...',
		'hotness_factors' => 'Tầm quan trọng cho các câu hỏi hot:',
		'hidden_title' => 'Ẩn',
		'ip_address_pages' => 'Địa chỉ IP trang',
		'layout_title' => 'Giao diện',
		'link_name' => 'Nội dung của link:',
		'link_new_window' => 'Mở một link trong một cửa sổ mới',
		'link_url' => 'link của URL  - tuyệt đối hay tương đối so với Q2A ban đầu:',
		'lists_title' => 'Danh sách',
		'mailing_complete' => 'Gửi thư hoàn tất',
		'mailing_explanation' => 'Các thành viên có quyền thôi nhận thông báo qua thư điện tử trong trang quản lý tài khoản.',
		'mailing_progress' => 'Đang gửi ^1 của ^2 các thành viên...',
		'mailing_title' => 'Gửi thư báo',
		'mailing_unsubscribe' => 'Liên kết để bỏ theo dõi qua thư điện tử sẽ được thêm vào cuối mỗi tin nhắn',
		'maintenance_admin_only' => 'Trang mạng của bạn là trong ^1bảo trì^2 và hiện không thể cho người dùng truy cập.',
		'maximum_x' => ' (tối đa ^)',
		'approve_users_title' => 'Phê duyệt thành viên',
		'module_x_database_init' => 'Các ^1 ^2 module yêu cầu một số ^3việc khởi tạo cơ sở dữ liệu^4.',
		'most_flagged_title' => 'Nội dung đã gán Flag',
		'mysql_version' => 'Phiên bản MySQL:',
		'nav_links_explanation' => 'Hiện các link chuyển hướng:',
		'nav_qa_is_home' => 'Q&A (link đến trang chủ)',
		'neat_urls_note' => ' (yêu cầu ^1htaccess^2 file)',
		'no_approve_found' => 'Không có nội dung đang đợi để phê duyệt',
		'no_classification' => 'Trống',
		'no_flagged_found' => 'Không có nội dung nào được phản ánh',
		'no_hidden_found' => 'Không có nội dung nào được ẩn',
		'no_image_gd' => 'Các phiên bản cài đặt của PHP được biên dịch không có hỗ trợ hình ảnh GD, vì vậy thành viên không thể tải hình đại diện lên trực tiếp.',
		'no_link' => 'Không có link',
		'no_multibyte' => 'Các phiên bản cài đặt PHP không được biên dịch không có hỗ trợ chuỗi multibyte. Tìm kiếm sẽ được ít ảnh hưởng đến các ký tự non-Roman.',
		'no_privileges' => 'Chỉ có người quản trị hệ thống mới có thể truy cập trang này.',
		'no_unapproved_found' => 'Không có thành viên nào đang đợi để phê duyệt',
		'not_logged_in' => 'Vui lòng ^1đăng nhập^2 như là người quản trị hệ thống để truy cập trang này.',
		'opposite_main_menu' => 'Ở phía xa cuối các tab trên cùng',
		'options_reset' => 'Tùy chọn reset',
		'options_saved' => 'Tùy chọn đã lưu',
		'options' => 'tùy chọn',
		'page_already_used' => 'Điều này đang được sử bởi một trang khác',
		'page_content_html' => 'Nội dung để hiện thị trong trang - có thể dùng HTML:',
		'page_default_slug' => 'tramg-^',
		'page_heading' => 'Tiêu đề đặt ở đầu trang:',
		'page_name' => 'Tên của trang (cũng cho phép sử dụng cho tab hoặc liên kết):',
		'page_slug' => 'Page slug (URL fragment):',
		'pages_explanation' => 'Bấm vào \'Thêm Trang\' để chỉnh sửa nội dung đến trang web Q2A của bạn,hoặc \'Thêm liên kêt\' để liên kết tới một trang web bất kỳ.',
		'pages_title' => 'Trang',
		'pause_mailing_button' => 'Tạm dụng mail',
		'per_ip_hour' => 'mỗi địa chỉ IP/giờ',
		'per_user_hour' => 'mỗi người dùng/giờ',
		'permissions_title' => 'Quyền',
		'permit_to_view' => 'Hiển thị cho:',
		'php_version' => 'Phiên bản PHP:',
		'pixels' => 'điểm ảnh',
		'plugin_module' => ' (module tiện ích: ^)',
		'plugin_pages_explanation' => 'Trang có khả năng tích hợp thêm các tiện ích ngoài:',
		'plugins_title' => 'Tiện ích ngoài',
		'points_defaults_shown' => 'Hiện mặc định dưới đây nhưng CHƯA ÁP DỤNG:',
		'points_required' => 'Điểm cần thiết để được nhận tiêu đề',
		'points_title' => 'Điểm',
		'points' => 'điểm',
		'position' => 'Vị trí:',
		'posting_title' => 'Bài đăng',
		'profile_fields' => 'Trường bổ sung trên trang thành viên hoặc trang đăng ký:',
		'q2a_build_date' => 'Ngày cập nhật:',
		'q2a_db_size' => 'Dung lượng cơ sở dữ liệu:',
		'q2a_db_version' => 'Phiên bản cơ sở dữ liệu của Q2A :',
		'q2a_latest_version' => 'Phiên bản mới nhất:',
		'q2a_version' => 'Phiên bản Question2Answer:',
		'question_lists' => 'Danh sách các câu hỏi',
		'question_pages' => 'Các trang câu hỏi',
		'recalc_categories_backpaths' => 'Tính toán lại đường dẫn URL cho ^1 của ^2 chủ đề...',
		'recalc_categories_complete' => 'Tất cả các chủ đề được tính toán lại thành công.',
		'recalc_categories_note' => ' - cho chủ đề bài đăng và đếm các chủ đề',
		'recalc_categories_recounting' => 'Đếm lại các câu hỏi cho ^1 của ^2 chủ đề...',
		'recalc_categories_updated' => 'Tính toán lại cho ^1 của ^2 bài đăng...',
		'recalc_categories' => 'Tính toán lại chủ đề',
		'recalc_points_complete' => 'Tất cả các điểm thành viên được tính toán lại thành công.',
		'recalc_points_note' => ' - cho thành viên xếp hạng và hiển thị điểm',
		'recalc_points_recalced' => 'Tính toán lại cho ^1 của ^2 thành viên...',
		'recalc_points_usercount' => 'Dự toán tổng số thành viên...',
		'recalc_points' => 'Tính toán lại số điểm của các thành viên',
		'recalc_posts_count' => 'Lấy tổng số các câu hỏi, các câu trả lời và các bình luận...',
		'recalc_stop' => 'Dừng việc tính toán',
		'recent_approve_title' => 'Nội dung gần đây đợi để để phê duyệt',
		'recent_hidden_title' => 'Ẩn nội dung gần đây',
		'recount_posts_as_recounted' => 'Đếm lại các câu trả lời và hot cho ^1 của ^2 bài đăng...',
		'recount_posts_complete' => 'Tất cả các bài đăng được đếm lại thành công.',
		'recount_posts_note' => ' - số câu trả lời, bình chọn, flags và hot cho mỗi bài đăng',
		'recount_posts_stop' => 'Dừng việc đếm lại',
		'recount_posts_votes_recounted' => 'Đếm lại bình chọn và flag cho ^1 của ^2 bài đăng...',
		'recount_posts' => 'Đếm lại bài đăng',
		'refill_events_complete' => 'Tất cả các dòng sự kiện được nạp lại thành công',
		'refill_events_note' => ' - cho mỗi thành viên của danh sách đã được cập nhật',
		'refill_events_refilled' => 'Nạp lại vào ^1 của ^2 các câu hỏi...',
		'refill_events' => 'Thống kê các hoạt động',
		'registration_fields' => 'thêm trường đăng ký',
		'reindex_content' => 'Đánh lại chỉ mục nội dung',
		'reindex_content_note' => ' - cho việc tìm kiếm và gợi ý các câu hỏi liên quan',
		'reindex_content_stop' => 'Dừng việc đánh lại chỉ mục',
		'reindex_pages_reindexed' => 'Đánh lại chỉ mục ^1 của ^2 trang...',
		'reindex_posts_complete' => 'Tất cả các bài đăng được đánh lại chỉ mục thành công.',
		'reindex_posts_reindexed' => 'Reindexed ^1 của ^2 posts...',
		'reindex_posts_wordcounted' => 'Đếm lại ^1 của ^2 từ...',
		'requires_php_version' => 'Vô hiệu hóa - yêu cầu PHP ^ hoặc sau đó',
		'requires_q2a_version' => 'Vô hiệu hóa - yêu cầu Question2Answer ^ hoặc sau đó',
		'reset_options_button' => 'Đặt về mặc định',
		'resume_mailing_button' => 'Hoãn gửi việc mail',
		'save_options_button' => 'Lưu Tùy chọn',
		'save_recalc_button' => 'Lưu và tính toán lại',
		'save_view_button' => 'Lưu và xem',
		'send_test_button' => 'Gửi nội dung đến tôi',
		'show_defaults_button' => 'Hiển thị mặc định',
		'show_on_register_form' => 'Hiển thị trường trên form đăng ký thành viên',
		'slug_bad_chars' => 'Slug này không chứa các ký tự: ^',
		'slug_reserved' => 'Slug này được dành riêng để sử dụng cho trang khác',
		'spam_title' => 'Nội dung rác',
		'start_mailing_button' => 'Bắt đầu gửi thư điện tử',
		'stats_title' => 'Thống kê',
		'stop_recalc_warning' => 'Hoạt động dọn dẹp cơ sở dữ liệu đang chạy. Nếu bạn đóng trang này ngay bây giờ, hoạt động này sẽ bị xảy ra lỗi.',
		'tag_pages' => 'Các nhãn',
		'tags_and_categories' => 'Phân loại theo Nhãn/Đề mục',
		'tags_not_shown' => 'Một vài câu hỏi có tag sẽ không được hiển thị.',
		'tags' => 'Nhãn',
		'test_sent_to_x' => 'Đoạn tin nhắn này sẽ được gửi đến ^',
		'title_already_used' => 'Giá trị này đang được sử dụng bởi một tiêu đề khác',
		'top_level_categories' => 'Các chủ đề đứng đầu:',
		'total_as' => 'Tổng cộng các câu trả lời:',
		'total_cs' => 'Tổng cộng các bình luận:',
		'total_qs' => 'Tổng cộng các câu hỏi:',
		'unnamed_plugin' => 'Chưa đặt tên Plugin',
		'upgrade_db' => 'Cơ sở dữ liệu Question2Answer cần được để ^1cập nhật^2 cho phiên bản này.',
		'url_format_note' => 'Các tùy chọn có nhãn ^ là định dạng tương thích với cấu hình hiện tại của trang web. Hãy chọn định dạng với nhãn ^ đầu tiên mà bạn thích từ trên xuống - việc này giúp tối ưu hóa dịch vụ tìm kiếm (SEO) của Google.',
		'user_pages' => 'Trang thành viên',
		'user_title' => 'Tiêu  đề thành viên - cho phép dùng HTML:',
		'user_titles' => 'Chức danh thành viên dựa trên điểm hoạt động:',
		'users_active' => 'Thành viên hoạt động:',
		'users_must_have' => 'Thành viên phải có',
		'users_posted' => 'Thành viên đăng bài:',
		'users_registered' => 'Đăng ký thành viên:',
		'users_title' => 'Thành viên',
		'users_voted' => 'Thành viên được bình chọn:',
		'version_get_x' => 'lấy ^',
		'version_requires_php' => '^1 yêu cầu PHP ^2', 
		'version_requires_q2a' => '^1 yêu cầu Q2A ^2', 
		'version_latest_unknown' => 'không rõ mới nhất',
		'version_latest' => 'mới nhất',
		'viewing_title' => 'Hiển thị',
		'widget_all_pages' => 'Hiển thị công cụ trong vị trí này trên tất cả các trang có khả năng',
		'widget_global_options' => ' - ^1tùy chọn^2',
		'widget_name' => 'Tên của công cụ:',
		'widget_no_positions' => 'Công cụ này đã được thêm đến mỗi vị trí có khả năng.',
		'widget_not_available' => 'Công cụ này không có khả năng. Điều này có thể bởi vì plugin cung cấp các widget đã lâu không cài đặt.',
		'widget_pages_explanation' => 'Hiện công cụ trong vị trí này trên trang theo dõi:',
		'widgets_explanation' => 'Các công cụ khả dụng:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/