<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-options.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for all options, as shown in admin center


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'allow_change_usernames' => 'Cho phép người dùng đã viết bài thay đổi tên tài khoản:',
		'allow_close_questions' => 'Cho phép đóng các câu hỏi thủ công:',
		'allow_login_email_only' => 'Chỉ đăng nhập bằng địa chỉ thư điện tử (không phải tên đăng nhập):', 
		'allow_multi_answers' => 'Cho phép mỗi tài khoản có nhiều câu trả lời:',
		'allow_no_category' => 'Cho phép câu hỏi không có hạng mục',
		'allow_no_sub_category' => 'Cho phép các câu hỏi có một hạng mục nhưng không có hạng mục con',
		'allow_private_messages' => 'Kích hoạt tính năng gửi tin nhắn cá nhân giữa người dùng:',
		'allow_user_walls' => 'Kích hoạt tính năng viết lên tường nhà người dùng khác:',
		'allow_self_answer' => 'Cho phép người dùng trả lời câu hỏi của mình:',
		'allow_view_q_bots' => 'Cho phép công cụ tìm kiếm để xem các trang câu hỏi',
		'approve_user_required' => 'Tất cả người dùng mới phải được chấp thuận:',
		'avatar_allow_gravatar' => 'Cho phép dùng ^2ảnh đại diện ^1Gravatar:',
		'avatar_allow_upload' => 'Cho phép người dùng tải lên ảnh đại diện:',
		'avatar_default_show' => 'Ảnh đại diện mặc định:',
		'avatar_message_list_size' => 'Kích thước ảnh đại diện trên danh sách tin nhắn:',
		'avatar_profile_size' => 'Kích thước ảnh đại diện trên trang lý lịch thành viên:',
		'avatar_q_list_size' => 'Kích thước ảnh đại diện trong danh sách câu hỏi:',
		'avatar_q_page_a_size' => 'Kích thước ảnh đại diện khi trả lời:',
		'avatar_q_page_c_size' => 'Kích thước ảnh đại diện khi bình luận:',
		'avatar_q_page_q_size' => 'Kích thước ảnh đại diện khi đặt câu hỏi:',
		'avatar_store_size' => 'Kích thước tối đa của avatar:',
		'avatar_users_size' => 'Kích thước ảnh đại diện trên trang danh sách thành viên:',
		'block_bad_words' => 'Các từ cấm sử dụng - phân cách bằng dấu cách hoặc dấu phẩy:',
		'block_ips_write' => 'Địa chỉ IP bị chặn - phân cách bằng dấu cách hoặc dấu phẩy:',
		'captcha_module' => 'Sử dụng hệ thống xác thực:',
		'captcha_on_anon_post' => 'Sử dụng hình ảnh xác thực cho bài viết của người dùng ẩn danh:',
		'captcha_on_feedback' => 'Sử dụng hình ảnh xác thực cho mẫu phản hồi:',
		'captcha_on_register' => 'Sử dụng hình ảnh xác thực cho đăng ký tài khoản:',
		'captcha_on_reset_password' => 'Sử dụng hình ảnh xác thực cho khôi phục lại mật khẩu:',
		'captcha_on_unapproved' => 'Sử dụng hình ảnh xác thực nếu tài khoản người dùng chưa được phê duyệt:',
		'captcha_on_unconfirmed' => 'Sử dụng hình ảnh xác thực nếu thư điện tử không được xác nhận:',
		'columns_tags' => 'Số cột trên trang Nhãn:',
		'columns_users' => 'Số cột trên trang của người dùng:',
		'comment_on_as' => 'Cho phép bình luận về câu trả lời:',
		'comment_on_qs' => 'Cho phép nhận xét về câu hỏi:',
		'confirm_user_emails' => 'Yêu cầu xác nhận thư điện tử của người dùng:',
		'confirm_user_required' => 'Tất cả người dùng mới phải xác nhận thư điện tử của họ:',
		'custom_home_content' => 'Nội dung trang chủ - có thể dùng cú pháp HTML:',
		'custom_home_heading' => 'Tiêu đề trang chủ:',
		'default_privacy' => 'Bảo mật riêng tư: Chúng tôi không chia sẻ hoặc kinh doanh địa chỉ thư điện tử của bạn.',
		'default_sidebar' => "Chào mừng bạn đến với ^, nơi bạn có thể đặt câu hỏi và nhận được câu trả lời từ các thành viên khác của cộng đồng.",
		'default_subject' => 'Một tin nhắn từ ^',
		'default_suffix' => 'Hỏi & đáp',
		'do_ask_check_qs' => 'Kiểm tra các câu hỏi tương tự khi đặt câu hỏi mới:',
		'do_close_on_select' => 'Đóng câu hỏi đã có câu trả lời tốt nhất:',
		'do_complete_tags' => 'Gợi ý nhãn khi đang nhập:',
		'do_count_q_views' => 'Đếm số lần xem câu hỏi:',
		'do_example_tags' => 'Gợi ý nhãn dựa trên nội dung câu hỏi:',
		'editor_for_as' => 'Soạn thảo mặc định cho câu trả lời:',
		'editor_for_cs' => 'Soạn thảo mặc định cho bình luận:',
		'editor_for_qs' => 'Soạn thảo mặc định cho câu hỏi:',
		'email_privacy' => 'Lưu ý bảo mật cho các địa chỉ thư điện tử - có thể dùng cú pháp HTML:',
		'extra_field_active' => 'Tuỳ chỉnh thêm trường nội dung khi đặt câu hỏi:',
		'extra_field_display_label' => 'Hiển thị thông tin thêm trên trang câu hỏi với nhãn:',
		'extra_field_display' => 'Hiển thị thông tin thêm trên trang câu hỏi',
		'feed_for_activity' => 'Trang thông tin của các hoạt động gần đây:',
		'feed_for_hot' => 'Trang thông tin của câu hỏi được quan tâm nhất:',
		'feed_for_qa' => 'Trang thông tin của câu hỏi và câu trả lời gần đây:',
		'feed_for_questions' => 'Trang thông tin của câu hỏi gần đây:',
		'feed_for_search' => 'Trang thông tin của kết quả tìm kiếm:',
		'feed_for_tag_qs' => 'Hiển thị danh sách câu hỏi cho mỗi nhãn:',
		'feed_for_unanswered' => 'Trang thông tin của câu hỏi chưa được trả lời:',
		'feed_full_text' => 'Văn bản đầy đủ ở trang thông tin:',
		'feed_number_items' => 'Chiều dài tối đa của trang thông tin:',
		'feed_per_category' => 'Trang thông tin cho mỗi hạng mục:',
		'feedback_email' => 'Địa chỉ thư điện tử của người quản trị - không hiển thị với người dùng thường:',
		'feedback_enabled' => 'Cung cấp trang phản hồi cho người dùng',
		'flagging_hide_after' => 'Tự động ẩn bài đăng có quá:',
		'flagging_notify_every' => 'Gửi thông báo cho tôi một lần nữa sau mỗi lần thêm:',
		'flagging_notify_first' => 'Gửi thông báo cho tôi nếu có một bài đăng được nhận:',
		'flagging_of_posts' => 'Cho phép bài viết được gắn cờ:',
		'follow_on_as' => 'Cho phép gợi ý các câu hỏi liên quan đến câu trả lời:',
		'from_email' => 'Địa chỉ người gửi cho các thông báo từ trang web:',
		'hot_weight_a_age' => 'Câu hỏi có một câu trả lời mới:',
		'hot_weight_answers' => 'Câu hỏi có nhiều câu trả lời:',
		'hot_weight_q_age' => 'Câu hỏi mới là:',
		'hot_weight_views' => 'Câu hỏi có nhiều lượt xem:',
		'hot_weight_votes' => 'Câu hỏi có nhiều lượt bình chọn:',
		'links_in_new_window' => 'Mở liên kết trong một cửa sổ mới:',
		'logo_height' => 'Chiều cao Logo:',
		'logo_show' => 'Hiển thị Logo trong tiêu đề trang',
		'logo_url' => 'Địa chỉ mạng của biểu tượng - tuyệt đối hoặc tương đối từ gốc trang hỏi đáp:',
		'logo_width' => 'Chiều dài Logo:',
		'mailing_body' => 'Văn bản chính:',
		'mailing_enabled' => 'Kích hoạt gởi thư điện tử cùng lúc cho tất cả người sử dụng',
		'mailing_from_email' => 'Từ địa chỉ thư điện tử:',
		'mailing_from_name' => 'Người quản trị:',
		'mailing_per_minute' => 'Giới hạn lượng thư điện tử được gửi cùng một lúc:',
		'mailing_subject' => 'Tiêu đề:',
		'match_1' => 'Rất sát nghĩa',
		'match_2' => 'Sát nghĩa',
		'match_3' => 'Mặc định',
		'match_4' => 'Nghĩa rộng',
		'match_5' => 'Nghĩa rất rộng',
		'match_ask_check_qs' => 'Câu hỏi tương tự phù hợp:',
		'match_example_tags' => 'Độ tương tự khi gợi ý nhãn:',
		'match_related_qs' => 'Câu hỏi liên quan phù hợp:',
		'max_len_q_title' => 'Chiều dài tối đa cho tiêu đề câu hỏi:',
		'max_num_q_tags' => 'Số lượng nhãn tối đa:',
		'max_rate_ip_as' => 'Tỷ lệ giới hạn của việc thêm câu trả lời:',
		'max_rate_ip_cs' => 'Tỷ lệ giới hạn của việc đăng bình luận:',
		'max_rate_ip_flags' => 'Tỷ lệ giới hạn cho việc gắn cờ bài viết:',
		'max_rate_ip_logins' => 'Tỷ lệ giới hạn của việc đăng nhập:',
		'max_rate_ip_messages' => 'Tỷ lệ giới hạn cho tin nhắn và bài viết cá nhân trên tường:',
		'max_rate_ip_qs' => 'Tỷ lệ giới hạn của việc đặt câu hỏi:',
		'max_rate_ip_registers' => 'Tỷ lệ giới hạn cho việc đăng ký tài khoản:',
		'max_rate_ip_uploads' => 'Tỷ lệ giới hạn của việc tập tin tải lên:',
		'max_rate_ip_votes' => 'Tỷ lệ giới hạn cho bình chọn:',
		'max_rate_user_as' => 'Câu trả lời tối đa cho mỗi người dùng trên mỗi giờ:',
		'max_rate_user_cs' => 'Bình luận ​​tối đa cho mỗi người dùng trên mỗi giờ:',
		'max_rate_user_flags' => 'Số cờ tối đa cho mỗi người dùng trên mỗi giờ:',
		'max_rate_user_messages' => 'Số tin nhắn tối đa cho mỗi người dùng trên mỗi giờ:',
		'max_rate_user_qs' => 'Số câu hỏi tối đa cho mỗi người dùng trên mỗi giờ:',
		'max_rate_user_uploads' => 'Số lần tải lên tối đa cho mỗi người dùng trên mỗi giờ:',
		'max_rate_user_votes' => 'Bình chọn tối đa cho mỗi người dùng trên mỗi giờ:',
		'min_len_a_content' => 'Chiều dài tối thiểu của câu trả lời:',
		'min_len_c_content' => 'Chiều dài tối thiểu của các bình luận:',
		'min_len_q_content' => 'Chiều dài tối thiểu của câu hỏi:',
		'min_len_q_title' => 'Chiều dài tối thiểu của tiêu đề câu hỏi:',
		'min_num_q_tags' => 'Số lượng nhãn tối thiểu:',
		'moderate_anon_post' => 'Sử dụng kiểm duyệt với bài viết của người dùng ẩn danh:',
		'moderate_by_points' => 'Sử dụng kiểm duyệt vơi người sử dụng có ít điểm:',
		'moderate_edited_again' => 'Kiểm duyệt lại sau khi chỉnh sửa bài viết:',
		'moderate_notify_admin' => 'Gửi thông báo cho tôi khi một bài cần kiểm duyệt:',
		'moderate_points_limit' => 'Sử dụng kiểm duyệt cho tài khoản có ít hơn:',
		'moderate_unapproved' => 'Sử dụng kiểm duyệt nếu tài khoản chưa được phê duyệt:',
		'moderate_unconfirmed' => 'Sử dụng kiểm duyệt nếu thư điện tử không được xác nhận:',
		'moderate_update_time' => 'Thời gian hiển thị trên bài đã được kiểm duyệt:',
		'moderate_users' => 'Kích hoạt kiểm duyệt (chấp thuận) của người sử dụng:',
		'neat_urls' => 'Cấu trúc địa chị mạng URL:',
		'notify_admin_q_post' => 'Gởi thông báo cho địa chỉ này khi có một câu hỏi được đăng',
		'notify_users_default' => 'Mặc định sẽ nhận thông báo qua thư điện tử:',
		'option_default' => 'Mặc định',
		'page_size_activity' => 'Chiều dài của trang chủ:',
		'page_size_ask_check_qs' => 'Số lượng câu hỏi tương tự tối đa hiển thị:',
		'page_size_ask_tags' => 'Số lượng hiển thị tối đa các nhãn gợi ý:',
		'page_size_home' => 'Chiều dài của trang chủ Hỏi & đáp:',
		'page_size_hot_qs' => 'Chiều dài của trang Tin nóng!:',
		'page_size_q_as' => 'Số lượng câu trả lời tối đa cho mỗi trang:',
		'page_size_qs' => 'Số lượng câu hỏi tối đa cho mỗi trang:',
		'page_size_related_qs' => 'Số lượng câu hỏi liên quan tối đa:',
		'page_size_search' => 'Kết quả tìm kiếm trên trang:',
		'page_size_tag_qs' => 'Các câu hỏi trên mỗi trang nhãn:',
		'page_size_tags' => 'Chiều dài của trang nhãn:',
		'page_size_una_qs' => 'Chiều dài của trang chưa được trả lời:',
		'page_size_users' => 'Chiều dài của trang người dùng:',
		'page_size_wall' => 'Số bài đăng trên mỗi trang:',
		'pages_prev_next' => 'Liên kết về trang trước / trang tiếp theo:',
		'permit_admins' => 'Quản trị viên',
		'permit_all' => 'Bất kỳ tài khoản nào',
		'permit_approve_users' => 'Phê duyệt tài khoản đã đăng ký:',
		'permit_approved' => 'Chỉ phê duyệt tài khoản người dùng',
		'permit_approved_points' => 'Phê duyệt tài khoản có đủ điểm',
		'permit_block' => 'Chặn hoặc hủy chặn người dùng từ địa chỉ IP này:',
		'permit_confirmed' => 'Đăng ký tài khoản với thư điện tử đã xác thực',
		'permit_create_admins' => 'Tạo tài khoản Quản trị viên:',
		'permit_create_eds_mods' => 'Tạo biên tập viên và điều hành viên:',
		'permit_create_experts' => 'Tạo chuyên viên:',
		'permit_delete_users' => 'Xóa tài khoản người dùng:',
		'permit_editors' => 'Biên tập viên, Điều hành viên, Quản trị viên',
		'permit_experts' => 'Chuyên viên, Biên tập viên, Điều hành viên, Quản trị viên',
		'permit_moderators' => 'Điều hành viên and Quản trị viên',
		'permit_points_confirmed' => 'Đã đăng ký & đã xác nhận thư điện tử & đủ điểm',
		'permit_points' => 'Đăng ký tài khoản người dùng với đủ điểm',
		'permit_see_emails' => 'Xem địa chỉ thư điện tử của người dùng:',
		'permit_supers' => 'Quản trị Hệ thống',
		'permit_users' => 'Thành viên đã đăng ký',
		'place_full_below_content' => 'Chiều rộng đầy đủ - Bên dưới nội dung',
		'place_full_below_footer' => 'Chiều rộng đầy đủ - Bên dưới cuối trang',
		'place_full_below_nav' => 'Chiều rộng đầy đủ - Bên dưới thanh điều hướng',
		'place_full_top' => 'Chiều rộng đầy đủ - Hiển thị ở đầu trang',
		'place_main_below_lists' => 'Khu vực chính - Bên dưới danh sách',
		'place_main_below_title' => 'Khu vực chính - Bên dưới tiêu đề trang',
		'place_main_bottom' => 'Khu vực chính - Bên dưới',
		'place_main_top' => 'Khu vực chính - Ở đầu',
		'place_side_below_categories' => 'Đặt ở cạnh biên - Bên dưới danh sách các danh mục',
		'place_side_below_sidebar' => 'Đặt ở cạnh biên',
		'place_side_last' => 'Đặt ở cạnh biên - Đặt ở cuối trang',
		'place_side_top' => 'Đặt ở cạnh biên - Đặt ở đầu trang',
		'points_a_selected' => 'Bạn có câu trả lời được bình chọn là hay nhất:',
		'points_a_voted_max_gain' => 'Giới hạn số lượng bình chọn trên mỗi câu trả lời:',
		'points_a_voted_max_loss' => 'Giới hạn số lượng không bình chọn trên mỗi câu trả lời:',
		'points_base' => 'Điểm cộng cho tất cả tài khoản mới:',
		'points_multiple' => 'Nhân tất cả điểm này cho:',
		'points_per_a_voted_down' => 'Điểm cho mỗi lượt rút phiếu cho câu trả lời của bạn:',
		'points_per_a_voted_up' => 'Điểm cho mỗi phiếu bình chọn cho câu trả lời của bạn:',
		'points_per_q_voted_down' => 'Điểm cho mỗi lượt rút phiếu cho câu hỏi của bạn:',
		'points_per_q_voted_up' => 'Điểm cho mỗi phiếu bình chọn cho câu hỏi của bạn:',
		'points_post_a' => 'Điểm cho một câu trả lời:',
		'points_post_q' => 'Điểm cho một câu hỏi:',
		'points_q_voted_max_gain' => 'Số điểm cộng tối đa cho mỗi câu hỏi:',
		'points_q_voted_max_loss' => 'Số điểm trừ tối đa cho mỗi câu hỏi:',
		'points_select_a' => 'Chọn một câu trả lời cho câu hỏi của bạn:',
		'points_vote_down_a' => 'Rút phiều bình chọn mỗi câu trả lời:',
		'points_vote_down_q' => 'Rút phiều bình chọn mỗi câu hỏi:',
		'points_vote_up_a' => 'Bình chọn cho mỗi câu trả lời:',
		'points_vote_up_q' => 'Bình chọn cho mỗi câu hỏi:',
		'q_urls_remove_accents' => 'Xóa các dấu hỏi trong liên kết URL:',
		'q_urls_title_length' => 'Chiều dài tiêu đề câu hỏi trong liên kết URL:',
		'register_notify_admin' => 'Gửi thư điện tử cho tôi khi có người dùng mới đăng ký:',
		'search_module' => 'Sử dụng hệ thống tìm kiếm:',
		'show_a_form_immediate' => 'Hiển thị trang trả lời ngay lập tức:',
		'show_always' => 'Luôn luôn',
		'show_c_reply_buttons' => 'Hiển thị nút trả lời bên cạnh bình luận:',
		'show_custom_answer' => 'Tùy chỉnh tin nhắn cho trang trả lời - có thể dùng cú pháp HTML:',
		'show_custom_ask' => 'Tùy chỉnh tin nhắn cho trang đặt câu hỏi - có thể dùng cú pháp HTML:',
		'show_custom_comment' => 'Tùy chỉnh tin nhắn cho trang bình luận - có thể dùng cú pháp HTML:',
		'show_custom_footer' => 'Tùy chỉnh nội dung HTML ở cuối mỗi trang:',
		'show_custom_header' => 'Tùy chỉnh nội dung HTML ở đầu mỗi trang:',
		'show_custom_home' => 'Tùy chỉnh nội dung trang chủ hỏi đáp',
		'show_custom_in_head' => 'Tùy chỉnh nội dung HTML của thẻ <head> ở mỗi trang:',
		'show_custom_register' => 'Tùy chỉnh tin nhắn ở trang đăng ký - có thể dùng cú pháp HTML:',
		'show_custom_sidebar' => 'Tùy chỉnh nội dung HTML ở mục thông tin trên mỗi trang:',
		'show_custom_sidepanel' => 'Tùy chỉnh nội dung HTML ở cạnh biên trên mỗi trang:',
		'show_custom_welcome' => 'Tùy chỉnh nội dung thông báo sẽ gởi đến tài khoản mới đăng ký:',
		'show_fewer_cs_count' => 'Nếu một phần bị ẩn, hiển thị nội dung gần đây nhất:',
		'show_fewer_cs_from' => 'Ẩn một phần bình luận nếu có nhiều hơn:',
		'show_full_date_days' => 'Hiển thị ngày đầy đủ sau:',
		'show_home_description' => 'Thêm mô tả <meta> cho trang chủ:',
		'show_if_no_as' => 'Nếu không có câu trả lời',
		'show_message_history' => 'Lưu trữ và hiển thị lịch sử tin nhắn:',
		'show_never' => 'Không bao giờ',
		'show_notice_visitor' => 'Thông báo ở đầu trang khi có khách viếng thăm lần đầu - có thể dùng cú pháp HTML:',
		'show_notice_welcome' => 'Thông báo ở đầu trang với tài khoản mới đăng ký - có thể dùng cú pháp HTML:',
		'show_selected_first' => 'Di chuyển câu trả lời được bình chọn là hay nhất lên đầu:',
		'show_url_links' => 'Phát hiện và liên kết các địa chỉ mạng trong bài viết:',
		'show_user_points' => 'Hiển thị điểm bên cạnh tên tài khoản:',
		'show_user_titles' => 'Hiển thị danh hiệu bên cạnh tên tài khoản:',
		'show_view_counts' => 'Hiển thị số lượt xem trong danh sách câu hỏi:',
		'show_view_count_q_page' => 'Hiển thị số lượt xem trên trang câu hỏi:',
		'show_when_created' => 'Hiển thị tuổi của người đăng bài:',
		'site_language' => 'Chọn ngôn ngữ:',
		'site_maintenance' => 'Tạm dừng hoạt động của trang web để bảo trì',
		'site_theme_mobile' => 'Chọn giao diện cho thiết bị di động:',
		'site_theme' => 'Chọn giao diện:',
		'site_title' => 'Tên trang chủ hỏi đáp:',
		'site_url' => 'Địa chỉ trang chủ:',
		'smtp_active' => 'Gửi thư điện tử thông qua giao thức SMTP thay vì dùng giao thức cục bộ',
		'smtp_address' => 'Địa chỉ SMTP:',
		'smtp_authenticate' => 'Tên đăng nhập và mật khẩu SMTP',
		'smtp_password' => 'Mật khẩu SMTP:',
		'smtp_port' => 'Cổng SMTP:',
		'smtp_secure_none' => 'Không',
		'smtp_secure' => 'Bảo mật kết nối SMTP:',
		'smtp_username' => 'Tên đăng nhập SMTP:',
		'sort_answers_by' => 'Sắp xếp câu trả lời theo:',
		'sort_time' => 'Thời gian',
		'sort_votes' => 'Phiếu bầu',
		'suspend_register_users' => 'Tạm hủy việc đăng ký tài khoản:',
		'tag_separator_comma' => 'Sử dụng dấu phấy để tách các nhãn với nhau:',
		'tags_or_categories' => 'Phân loại câu hỏi:',
		'time_approved' => 'Thời gian bài được duyệt',
		'time_written' => 'Thời gian bài được viết',
		'votes_separated' => 'Phân tách phiếu chống và phiếu ủng hộ:',
		'voting_on_as' => 'Cho phép bình chọn câu trả lời:',
		'voting_on_q_page_only' => 'Chỉ cho phép bình chọn câu hỏi:',
		'voting_on_qs' => 'Cho phép bình chọn câu hỏi:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/