<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-main.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1 câu trả lời',
		'1_comment' => '1 bình luận',
		'1_day' => '1 ngày',
		'1_disliked' => '1 không thích',
		'1_flag' => '1 báo cáo vi phạm',
		'1_hour' => '1 giờ',
		'1_liked' => '1 thích',
		'1_minute' => '1 phút',
		'1_month' => '1 tháng',
		'1_point' => '1 điểm',
		'1_question' => '1 câu hỏi',
		'1_second' => '1 giây',
		'1_tag' => '1 tag',
		'1_user' => '1 thành viên',
		'1_view' => '1 lượt xem',
		'1_vote' => '1 phiếu',
		'1_week' => '1 tuần',
		'1_year' => '1 năm',
		'add_category_x_favorites' => 'Thêm chủ đề "^" vào mục yêu thích của tôi',
		'add_favorites' => 'Thêm vào mục yêu thích của tôi',
		'add_tag_x_favorites' => 'Thêm tag ^ vào mục yêu thích của tôi',
		'all_categories' => 'Tất cả chủ đề',
		'anonymous' => 'Khách',
		'answer_edited' => 'câu trả lời đã sửa',
		'answer_reshown' => 'câu trả lời đã hiện lại',
		'answer_selected' => 'câu trả lời được chọn hay nhất',
		'answered_qs_in_x' => 'Các câu hỏi được trả lời nhiều nhất trong ^',
		'answered_qs_title' => 'Các câu hỏi được trả lời nhiều nhất',
		'answered' => 'đã trả lời',
		'asked_related_q' => 'đã hỏi câu hỏi liên quan',
		'asked' => 'đã hỏi',
		'by_x' => 'bởi ^',
		'cancel_button' => 'Hủy bỏ',
		'closed' => 'đã đóng',
		'comment_edited' => 'bình luận đã được sửa',
		'comment_moved' => 'bình luận đã chuyển',
		'comment_reshown' => 'bình luận đã hiện lại',
		'commented' => 'đã bình luận',
		'date_day_min_digits' => 1, // 1 or 2
		'date_format_other_years' => '^day ^month, ^year',
		'date_format_this_year' => '^day ^month',
		'date_month_1' => 'Tháng 1',
		'date_month_2' => 'Tháng 2',
		'date_month_3' => 'Tháng 3',
		'date_month_4' => 'Tháng 4',
		'date_month_5' => 'Tháng 5',
		'date_month_6' => 'Tháng 6',
		'date_month_7' => 'Tháng 7',
		'date_month_8' => 'Tháng 8',
		'date_month_9' => 'Tháng 9',
		'date_month_10' => 'Tháng 10',
		'date_month_11' => 'Tháng 11',
		'date_month_12' => 'Tháng 12',
		'date_year_digits' => 4, // 2 or 4
		'edited' => 'sửa nội dung',
		'field_required' => 'Xin vui lòng điền vào ô trống',
		'general_error' => 'Một lỗi của máy chủ đã xảy ra - xin vui lòng thử lại.',
		'hidden' => 'đã ẩn',
		'highest_users' => 'Bảng xếp hạng thành viên',
		'hot_qs_in_x' => 'Câu hỏi Hot trong ^',
		'hot_qs_title' => 'Câu hỏi Hot',
		'image_not_read' => 'Bức ảnh này không đúng định dạng chuẩn. Xin vui lòng tải lên các file: ^',
		'image_too_big_x_pc' => 'Kích cỡ ảnh này quá lớn. Xin vui lòng giảm kích cỡ xuống ^% và thử lại.',
		'in_category_x' => 'trong ^',
		'ip_address_x' => 'Địa chỉ IP ^',
		'logged_in_x' => 'Xin chào ^',
		'max_length_x' => 'Độ dài tối đa là ^ ký tự',
		'me' => 'tôi',
		'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'Xin vui lòng cung cấp thêm thông tin - ít nhất ^ ký tự',
		'moved' => 'đã chuyển',
		'nav_account' => 'Tài khoản',
		'nav_activity' => 'Hoạt động gần đây',
		'nav_admin' => 'Admin',
		'nav_ask' => 'Đặt câu hỏi',
		'nav_categories' => 'Chủ đề',
		'nav_feedback' => 'Gửi phản hồi',
		'nav_home' => 'Trang chủ',
		'nav_hot' => 'Hot!',
		'nav_login' => 'Đăng nhập',
		'nav_logout' => 'Thoát',
		'nav_most_answers' => 'Trả lời nhiều nhất',
		'nav_most_recent' => 'Gần đây',
		'nav_most_views' => 'Xem nhiều nhất',
		'nav_most_votes' => 'Nhiều phiếu nhất',
		'nav_no_answer' => 'Chưa trả lời',
		'nav_no_selected_answer' => 'Chưa có câu trả lời hay nhất',
		'nav_no_upvoted_answer' => 'Câu trả lời chưa có phiếu',
		'nav_qa' => 'Q&A',
		'nav_qs' => 'Danh mục',
		'nav_register' => 'Đăng ký',
		'nav_tags' => 'Tags',
		'nav_unanswered' => 'Trả lời câu hỏi',
		'nav_updates' => 'Cập nhật',
		'nav_users' => 'Thành viên',
		'no_active_users' => 'Không có thành viên nào được tìm thấy',
		'no_answers_found' => 'Không có câu trả lời nào được tìm thấy',
		'no_answers_in_x' => 'Không có câu trả lời trong ^',
		'no_categories_found' => 'Không có chủ đề nào được tìm thấy',
		'no_category' => 'Không có chủ đề',
		'no_comments_found' => 'Không có bình luận nào được tìm thấy',
		'no_comments_in_x' => 'Không có bình luận nào trong ^',
		'no_questions_found' => 'Chưa có câu hỏi nào cả!',
		'no_questions_in_x' => '^ - Không có câu hỏi nào',
		'no_related_qs_title' => 'Không có câu hỏi liên quan nào được tìm thấy',
		'no_results_for_x' => 'Không có kết quả nào được tìm thấy cho ^',
		'no_tags_found' => 'Không tìm thấy Tag',
		'no_una_questions_found' => 'Không có câu hỏi chưa được trả lời nào được tìm thấy',
		'no_una_questions_in_x' => 'Không có câu hỏi chưa được trả lời trong ^',
		'no_unselected_qs_found' => 'Không có câu hỏi nào thiếu câu trả lời hay nhất được tìm thấy',
		'no_unupvoteda_qs_found' => 'Không có câu hỏi nào thiếu câu trả lời có bình chọn được tìm thấy',
		'page_label' => 'Trang:',
		'page_next' => 'sau',
		'page_not_found' => 'Trang không được tìm thấy',
		'page_prev' => 'trước',
		'popular_tags' => 'Tag phổ biến nhất',
		'questions_tagged_x' => '^ - Các câu hỏi được Tag gần đây',
		'recategorized' => 'Đã chọn lại chủ đề',
		'recent_activity_in_x' => '^ - Hoạt động gần đây',
		'recent_activity_title' => 'Hoạt động gần đây',
		'recent_as_in_x' => 'Các câu hỏi đã được trả lời gần đây trong ^',
		'recent_as_title' => 'Các câu hỏi đã được trả lời gần đây',
		'recent_cs_in_x' => 'Những bình luận gần đây trong ^',
		'recent_cs_title' => 'Những bình luận gần đây',
		'recent_qs_as_in_x' => '^ - Các câu hỏi và trả lời gần đây',
		'recent_qs_as_title' => 'Các câu hỏi và trả lời gần đây',
		'recent_qs_in_x' => '^ - Các câu hỏi gần đây',
		'recent_qs_title' => 'Các câu hỏi gần đây',
		'related_qs_title' => 'Các câu hỏi liên quan',
		'remove_favorites' => 'Xóa khỏi mục yêu thích của tôi',
		'remove_x_favorites' => 'Xóa ^ khỏi mục yêu thích của tôi',
		'reopened' => 'đã mở lại',
		'reshown' => 'đã hiện lại',
		'results_for_x' => 'Kết quả tìm kiếm: ^',
		'retagged' => 'đã tag lại',
		'save_button' => 'Lưu thay đổi',
		'search_button' => 'Tìm kiếm',
		'search_explanation' => 'Xin vui lòng nhập từ khóa vào ô tìm kiếm và thử lại.',
		'search_title' => 'Kết quả tìm kiếm',
		'selected' => 'được bầu chọn là câu hỏi hay nhất',
		'send_button' => 'Gửi',
		'suggest_ask' => '^1Hãy đặt câu hỏi^2 để được trợ giúp.',
		'suggest_category_qs' => 'Để xem thêm, hãy bấm vào tất cả ^1các câu hỏi trong chủ đề này^2.',
		'suggest_qs_tags' => 'Để xem thêm, hãy bấm vào ^1danh sách đầy đủ các câu hỏi^2 or ^3các tag phổ biến^4.',
		'suggest_qs' => 'Để xem thêm, hãy bấm vào ^1danh sách đầy đủ các câu hỏi^2.',
		'unanswered_qs_in_x' => 'Các câu hỏi thiếu câu trả lời trong ^',
		'unanswered_qs_title' => 'Các câu hỏi gần đây thiếu câu trả lời',
		'unselected_qs_in_x' => 'Các câu hỏi thiếu câu trả lời hay nhất trong ^',
		'unselected_qs_title' => 'Các câu hỏi gần đây thiếu câu trả lời hay nhất',
		'unupvoteda_qs_in_x' => 'Các câu hỏi thiếu câu trả lời được bỏ phiếu trong ^',
		'unupvoteda_qs_title' => 'Các câu hỏi gần đây thiếu câu trả lời được bỏ phiếu',
		'upload_limit' => 'Tải lên quá nhiều - xin vui lòng thử lại sau 1 tiếng nữa',
		'view_q_must_confirm' => 'Xin vui lòng ^5xác nhận địa chỉ Email^6 để xem câu hỏi.',
		'view_q_must_login' => 'Xin vui lòng ^1đăng nhập^2 hoặc ^3đăng ký^4 để xem câu hỏi.',
		'viewed_qs_in_x' => 'Các câu hỏi được xem nhiều nhất trong ^',
		'viewed_qs_title' => 'Các câu hỏi nhiều người xem nhất',
		'vote_disabled_down' => 'Rút phiếu chỉ có thể cho một vài thành viên',
		'vote_disabled_hidden_a' => 'Bạn không thể bỏ phiếu cho câu trả lời bị ẩn',
		'vote_disabled_hidden_q' => 'Bạn không thể bỏ phiếu cho câu hỏi bị ẩn',
		'vote_disabled_level' => 'Bỏ phiếu chỉ có thể cho một vài thành viên',
		'vote_disabled_my_a' => 'Bạn không thể bỏ phiếu cho câu trả lời của bạn',
		'vote_disabled_my_q' => 'Bạn không thể bỏ phiếu cho câu hỏi của bạn',
		'vote_disabled_q_page_only' => 'Xin vui lòng xem câu hỏi này để bỏ phiếu',
		'vote_down_must_confirm' => 'Xin vui lòng ^5xác nhận địa chỉ Email^6 để rút phiếu.',
		'vote_down_popup' => 'Bấm để rút phiếu',
		'vote_limit' => 'Quá nhiều phiếu được nhận - xin vui lòng thử lại sau 1 tiếng nữa',
		'vote_must_confirm' => 'Xin vui lòng ^5xác nhận Email^6 để bỏ phiếu.',
		'vote_must_login' => 'Xin vui lòng ^1đăng nhập^2 hoặc ^3đăng ký^4 để bỏ phiếu.',
		'vote_not_allowed' => 'Bỏ phiếu tại đây không được phép',
		'vote_up_popup' => 'Bấm để bỏ phiếu',
		'voted_down_popup' => 'Bạn đã rút phiếu - bấm để rút lại',
		'voted_qs_in_x' => 'Các câu hỏi có số phiếu cao nhất trong ^',
		'voted_qs_title' => 'Các câu hỏi có số phiếu cao nhất',
		'voted_up_popup' => 'Bạn đã bỏ phiếu - bấm để rút lại',
		'x_ago' => '^ cách đây',
		'x_answers' => '^ câu trả lời',
		'x_comments' => '^ bình luận',
		'x_days' => '^ ngày',
		'x_disliked' => '^ không thích',
		'x_flags' => '^ báo cáo vi phạm',
		'x_hours' => '^ giờ',
		'x_liked' => '^ thích',
		'x_minutes' => '^ phút',
		'x_months' => '^ tháng',
		'x_points' => '^ điểm',
		'x_questions' => '^ câu hỏi',
		'x_seconds' => '^ giây',
		'x_tags' => '^ tags',
		'x_users' => '^ thành viên',
		'x_views' => '^ lượt xem',
		'x_votes' => '^ phiếu',
		'x_weeks' => '^ tuần',
		'x_years' => '^ năm',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/