<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-question.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases for question page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer_title' => '1 câu trả lời',
		'a_convert_to_c_on' => 'Chuyển đổi câu trả lời này vào 1 bình luận:',
		'a_convert_to_c' => 'Chuyển đổi câu trả lời này vào 1 bình luận',
		'a_convert_warn_cs' => 'Cảnh báo: Sự chuyển đổi này không thể khôi phục lại và ngoài ra nó còn chuyển cả các bình luận của câu trả lời này.',
		'a_convert_warn' => 'Cảnhh báo: Sự chuyển đổi này không thể khôi phục lại.',
		'a_notify_email' => 'Gửi Email cho tôi vào địa chỉ này nếu câu trả lời của tôi được bầu chọn hay nhất hoặc được bình luận:',
		'a_notify_label' => 'Gửi Email cho tôi nếu câu trả lời của tôi được bầu chọn hay nhất hoặc được bình luận',
		'a_notify_x_label' => 'Gửi Email cho tôi (^) nếu câu trả lời của tôi được bầu chọn hay nhất hoặc được bình luận',
		'a_waiting_your_approval' => 'Câu trả lời này đang chờ sự chấp thuận của bạn',
		'a_your_waiting_approval' => 'Câu trả lời của bạn sẽ được kiểm tra và chấp thuận trong thời gian sớm nhất có thể.',
		'add_answer_button' => 'Thêm câu trả lời',
		'add_comment_button' => 'Thêm bình luận',
		'add_q_favorites' => 'Thêm câu hỏi này vào mục yêu thích của tôi',
		'answer_button' => 'trả lời câu hỏi',
		'answer_limit' => 'Quá nhiều câu trả lời được nhận - xin vui lòng thử lại sau 1 tiếng nữa',
		'answer_must_confirm' => 'Xin vui lòng ^5xác nhận địa chỉ Email^6 để trả lời câu hỏi này.',
		'answer_must_login' => 'Xin vui lòng ^1đăng nhập^2 hoặc ^3đăng ký^4 để trả lời câu hỏi này.',
		'answer_q_popup' => 'Trả lời câu hỏi này',
		'approve_button' => 'đồng ý',
		'ask_button' => 'Đặt câu hỏi',
		'ask_follow_from_a' => 'Câu hỏi của bạn sẽ được liên quan đến câu trả lời này:',
		'ask_follow_title' => 'Đặt câu hỏi liên quan',
		'ask_limit' => 'Quá nhiều câu hỏi được nhận - xin vui lòng thử lại sau 1 tiếng nữa',
		'ask_must_confirm' => 'Xin vui lòng ^5xác nhận địa chỉ Email^6 để đặt câu hỏi.',
		'ask_must_login' => 'Xin vui lòng ^1đăng nhập^2 hoặc ^3đăng ký^4 để đặt câu hỏi.',
		'ask_same_q' => 'Trước khi đặt câu hỏi, xin vui lòng kiểm tra các câu hỏi tương tự sau:',
		'ask_title' => 'Đặt câu hỏi',
		'c_notify_email' => 'Gửi Email cho tôi vào địa chỉ này nếu 1 bình luận được thêm vào sau đó:',
		'c_notify_label' => 'Gửi Email cho tôi nếu 1 bình luận được thêm vào sau đó',
		'c_notify_x_label' => 'Gửi Email cho tôi (^) nếu 1 bình luận được thêm vào sau đó',
		'c_waiting_your_approval' => 'Bình luận này đang chờ sự chấp thuận của bạn',
		'c_your_waiting_approval' => 'Bình luận của bạn sẽ được kiểm tra và chấp thuận trong thời gian sớm nhất có thể.',
		'category_js_note' => 'Để chọn một chủ đề bất kỳ, xin vui lòng bật Javascript trong trình duyệt của bạn.',
		'category_required' => 'Xin vui lòng chọn 1 chủ đề',
		'claim_button' => 'Tôi đã viết nó',
		'clear_flags_button' => 'xóa báo cáo vi phạm',
		'clear_flags_popup' => 'Xóa báo cáo vi phạm bởi tất cả thành viên',
		'close_button' => 'đóng',
		'close_duplicate_error' => 'Câu hỏi trùng lặp không thể tìm thấy - xin vui lòng điền số trong đường dẫn của câu hỏi, ví dụ: 123.',
		'close_duplicate' => 'Có sự trùng lặp với câu hỏi khác',
		'close_form_button' => 'Đóng câu hỏi',
		'close_form_title' => 'Đóng câu hỏi này',
		'close_original_note' => 'Ngoài ra bạn có thể điền số của câu hỏi (số trong đường dẫn), ví dụ: 123.',
		'close_original_title' => 'Đường dẫn của câu hỏi gốc:',
		'close_q_popup' => 'Đóng câu hỏi này để không chấp nhận những câu trả lời mới',
		'close_reason_title' => 'Lý do đóng câu hỏi này:',
		'closed_as_duplicate' => 'đã đóng do sự trùng lặp với:',
		'closed_with_note' => 'đã đóng với lý do:',
		'comment_a_popup' => 'Thêm bình luận lên câu trả lời này',
		'comment_button' => 'Bình Luận - xin hãy cho chúng tôi biết suy nghĩ của bạn về câu trả lời này',
		'comment_limit' => 'Quá nhiều bình luận được nhận - xin vui lòng thử lại sau 1 tiếng nữa',
		'comment_must_confirm' => 'Xin vui lòng ^5xác nhận địa chỉ Email^6 để thêm bình luận.',
		'comment_must_login' => 'Xin vui lòng ^1đăng nhập^2 hoặc ^3đăng ký^4 để thêm bình luận.',
		'comment_on_a' => 'Lên câu trả lời: ',
		'comment_on_q' => 'Lên câu hỏi: ',
		'comment_q_popup' => 'Thêm bình luận lên câu hỏi này',
		'delete_a_popup' => 'Xóa câu trả lời này vĩnh viễn',
		'delete_button' => 'xóa',
		'delete_c_popup' => 'Xóa bình luận này vĩnh viễn',
		'delete_q_popup' => 'Xóa câu hỏi này vĩnh viễn',
		'duplicate_content' => 'Thông tin của bạn bị trùng lặp.',
		'edit_a_popup' => 'Sửa câu trả lời này',
		'edit_a_title' => 'Sửa câu trả lời',
		'edit_button' => 'sửa',
		'edit_c_popup' => 'Sửa bình luận này',
		'edit_c_title' => 'Sửa bình luận',
		'edit_must_confirm' => 'Xin vui lòng ^5xác nhận địa chỉ Email^6 để sửa nó.',
		'edit_must_login' => 'Xin vui lòng ^1đăng nhập^2 hoặc ^3đăng ký^4 để sửa nó.',
		'edit_q_popup' => 'Sửa câu hỏi này',
		'edit_q_title' => 'Sửa câu hỏi',
		'example_tags' => 'Ví dụ tags: ',
		'flag_a_popup' => 'Báo cáo vi phạm câu trả lời này do spam hoặc không thích hợp',
		'flag_button' => 'báo cáo vi phạm',
		'flag_c_popup' => 'Báo cáo vi phạm bình luận này do spam hoặc không thích hợp',
		'flag_hide_button' => 'báo cáo vi phạm và ẩn đi',
		'flag_limit' => 'Quá nhiều báo cáo vi phạm - xin vui lòng thử lại sau 1 tiếng nữa',
		'flag_must_confirm' => 'Xin vui lòng ^5xác nhận địa chỉ Email^6 để báo cáo vi phạm.',
		'flag_must_login' => 'Xin vui lòng ^1đăng nhập^2 hoặc ^3đăng ký^4 để báo cáo vi phạm.',
		'flag_not_allowed' => 'Không cho phép báo cáo vi phạm',
		'flag_q_popup' => 'Báo cáo vi phạm câu hỏi này do spam hoặc không thích hợp',
		'follow_a_popup' => 'Đặt 1 câu hỏi mới liên quan đến câu trả lời này',
		'follow_button' => 'đặt 1 câu hỏi mới liên quan đến câu trả lời này',
		'follows_a' => 'liên quan đến câu trả lời tại đây:',
		'follows_q' => 'về câu hỏi:',
		'hide_a_popup' => 'Ẩn câu trả lời này',
		'hide_button' => 'ẩn',
		'hide_c_popup' => 'Ẩn bình luận này',
		'hide_q_popup' => 'Ẩn câu hỏi này',
		'matching_tags' => 'Các tag phù hợp: ',
		'max_tags_x' => 'Chỉ được phép đặt tối đa ^ tags',
		'min_tags_x' => 'Xin vui lòng cung cấp ít nhất ^ tag/s',
		'notify_email_note' => 'Chính sách bảo mật: Địa chỉ Email của bạn chỉ được sử dụng để gửi những thông báo này.',
		'q_category_label' => 'Chủ đề:',
		'q_content_label' => 'Thêm thông tin cho câu hỏi:',
		'q_hidden_author' => 'Câu hỏi này đã được ẩn đi bởi người viết',
		'q_hidden_flagged' => 'Câu hỏi này đã bị báo cáo vi phạm và ẩn đi',
		'q_hidden_other' => 'Câu hỏi này đã được ẩn',
		'q_notify_email' => 'Gửi Email cho tôi vào địa chỉ này nếu câu hỏi của tôi được trả lời hoặc bình luận:',
		'q_notify_label' => 'Gửi Email cho tôi nếu câu hỏi của tôi được trả lời hoặc bình luận',
		'q_notify_x_label' => 'Gửi Email cho tôi (^) nếu câu hỏi của tôi được trả lời hoặc bình luận',
		'q_tags_comma_label' => 'Tag - sử dụng dấu phẩy để phân chia tag (,) :',
		'q_tags_label' => 'Tag - sử dụng dấu gạch ngang để viết nhiều tag:',
		'q_title_label' => 'Viết câu hỏi vào ô dưới đây:',
		'q_waiting_approval' => 'Câu hỏi này đang chờ duyệt',
		'q_waiting_your_approval' => 'Câu hỏi này đang chờ bạn duyệt',
		'q_your_waiting_approval' => 'Câu hỏi của bạn sẽ được kiểm tra và chấp thuận trong thời gian sớm nhất có thể.',
		'recat_button' => 'thay đổi chủ đề',
		'recat_popup' => 'Thay đổi chủ đề của câu hỏi này',
		'recat_q_title' => 'Thay đổi chủ đề câu hỏi',
		'reject_button' => 'loại bỏ',
		'remove_q_favorites' => 'Xóa câu hỏi này khỏi mục yêu thích của tôi',
		'reopen_button' => 'mở lại',
		'reply_button' => 'hồi âm',
		'reply_c_popup' => 'Hồi âm bình luận này',
		'reshow_button' => 'hiện lại',
		'retag_button' => 'tag lại',
		'retag_cat_popup' => 'Thay đổi chủ đề hoặc tag của câu hỏi này',
		'retag_popup' => 'Thay đổi tag của câu hỏi này',
		'retag_q_title' => 'Tag lại cho câu hỏi',
		'select_popup' => 'Bấm vào đây để chọn câu trả lời hay nhất',
		'select_text' => 'Câu trả lời hay nhất',
		'show_1_comment' => 'Hiện 1 bình luận',
		'show_1_previous_comment' => 'Hiện 1 bình luận trước đây',
		'show_x_comments' => 'Hiện ^ bình luận',
		'show_x_previous_comments' => 'Hiện ^ bình luận trước đây',
		'unflag_button' => 'xóa báo cáo vi phạm',
		'unflag_popup' => 'Xóa báo cáo vi phạm mà bạn đã gửi',
		'unselect_popup' => 'Bấm để xóa bầu chọn câu trả lời hay nhất',
		'x_answers_title' => '^ Câu trả lời',
		'your_answer_title' => 'Câu trả lời của bạn',
		'your_comment_a' => 'Xin hãy cho chúng tôi biết suy nghĩ của bạn về câu trả lời này:',
		'your_comment_q' => 'Xin hãy cho chúng tôi biết suy nghĩ của bạn về câu hỏi này:',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/