<?php
	
/*
	Question2Answer (c) Gideon Greenspan

	http://www.question2answer.org/

	
	File: qa-include/qa-lang-main.php
	Version: See define()s at top of qa-include/qa-base.php
	Description: Language phrases commonly used throughout Q2A
	Translate to Vietnamese: Team NTHQ - University of Information Technology Ho Chi Minh city.
	Team NTHQ:
	Nam Vu Giang
	Hung Huynh Ngoc - 11520573
	Thai Nguyen Thanh - 11520357
	Quan Tran Anh - 11520305


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.
	
	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1 Trả lời',
		'1_comment' => '1 Bình luận',
		'1_day' => '1 Ngày',
		'1_disliked' => '1 Không thích',
		'1_flag' => '1 Phản ánh',
		'1_hour' => '1 Giờ',
		'1_liked' => '1 Thích',
		'1_minute' => '1 Phút',
		'1_month' => '1 Tháng',
		'1_point' => '1 Điểm',
		'1_question' => '1 Câu hỏi',
		'1_second' => '1 Giây',
		'1_tag' => '1 Nhãn',
		'1_user' => '1 Thành viên',
		'1_view' => '1 Lượt xem',
		'1_vote' => '1 Phiếu',
		'1_week' => '1 Tuần',
		'1_year' => '1 Năm',
		'add_category_x_favorites' => 'Thêm ^ vào chủ đề yêu thích',
		'add_favorites' => 'Thêm vào yêu thích',
		'add_tag_x_favorites' => 'Thêm tag ^ vào yêu thích',
		'all_categories' => 'Tất cả phân loại',
		'anonymous' => 'vô danh',
		'answer_edited' => 'câu trả lời đã cập nhật',
		'answer_reshown' => 'câu trả lời đã hiện lại',
		'answer_selected' => 'câu trả lời được chọn hay nhất',
		'answered_qs_in_x' => 'Các câu hỏi được trả lời nhiều nhất trong ^',
		'answered_qs_title' => 'Các câu hỏi được trả lời nhiều nhất',
		'answered' => 'Đã trả lời',
		'asked_related_q' => 'Đã hỏi câu hỏi liên quan',
		'asked' => 'Đã hỏi',
		'by_x' => 'bởi ^',
		'cancel_button' => 'Hủy bỏ',
		'closed' => 'Đã đóng',
		'comment_edited' => 'Bình luận đã được cập nhật',
		'comment_moved' => 'Bình luận đã chuyển',
		'comment_reshown' => 'Bình luận đã hiện lại',
		'commented' => 'Đã bình luận',
		'date_day_min_digits' => 2, // 1 or 2
		'date_format_other_years' => '^day/^month/^year',
		'date_format_this_year' => '^day/^month ',
		'date_month_1' => '1',
		'date_month_2' => '2',
		'date_month_3' => '3',
		'date_month_4' => '4',
		'date_month_5' => '5',
		'date_month_6' => '6',
		'date_month_7' => '7',
		'date_month_8' => '8',
		'date_month_9' => '9',
		'date_month_10' => '10',
		'date_month_11' => '11',
		'date_month_12' => '12',
		'date_year_digits' => 4, // 2 or 4
		'edited' => 'cập nhật',
		'field_required' => 'Xin vui lòng điền vào ô trống',
		'general_error' => 'Một lỗi của máy chủ đã xảy ra - xin vui lòng thử lại.',
		'hidden' => 'đã ẩn',
		'highest_users' => 'Bảng Xếp hạng Thành viên',
		'hot_qs_in_x' => 'Câu hỏi Hot trong ^',
		'hot_qs_title' => 'Câu hỏi Hot',
		'image_not_read' => 'Bức ảnh này không đúng định dạng chuẩn. Xin vui lòng tải lên các file: ^',
		'image_too_big_x_pc' => 'Kích cỡ ảnh này quá lớn. Xin vui lòng giảm kích cỡ xuống ^% và thử lại.',
		'in_category_x' => 'trong ^',
		'ip_address_x' => 'Địa chỉ IP ^',
		'logged_in_x' => 'Xin chào ^',
		'max_length_x' => 'Độ dài tối đa là ^ ký tự',
		'me' => 'tôi',
		'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'Xin vui lòng cung cấp thêm thông tin - ít nhất ^ ký tự',
		'max_upload_size_x' => 'Kích cỡ tải lên tối đa là ^',
		'moved' => 'đã chuyển',
		'nav_activity' => 'Hoạt động gần đây',
		'nav_admin' => 'Quản trị',
		'nav_ask' => 'Đặt câu hỏi',
		'nav_categories' => 'Chủ đề',
		'nav_feedback' => 'Gửi phản hồi',
		'nav_home' => 'Trang chủ',
		'nav_hot' => 'Tin nóng',
		'nav_login' => 'Đăng nhập',
		'nav_logout' => 'Đăng xuất',
		'nav_most_answers' => 'Nhiều câu trả lời nhất',
		'nav_most_recent' => 'Gần đây',
		'nav_most_views' => 'Xem nhiều nhất',
		'nav_most_votes' => 'Bình chọn nhiều nhất',
		'nav_no_answer' => 'Chưa có câu trả lời',
		'nav_no_selected_answer' => 'Chưa có câu trả lời hay nhất',
		'nav_no_upvoted_answer' => 'Câu trả lời chưa có bình chọn',
		'nav_qa' => 'H&Đ',
		'nav_qs' => 'Câu hỏi',
		'nav_register' => 'Đăng ký',
		'nav_tags' => 'Nhãn',
		'nav_unanswered' => 'Chưa trả lời',
		'nav_updates' => 'Cập Nhật',
		'nav_users' => 'Thành viên',
		'no_active_users' => 'Không có thành viên nào được tìm thấy',
		'no_answers_found' => 'Không có câu trả lời nào được tìm thấy',
		'no_answers_in_x' => 'Không có câu trả lời trong ^',
		'no_categories_found' => 'Không có chủ đề nào được tìm thấy',
		'no_category' => 'Không có chủ đề',
		'no_comments_found' => 'Không tìm thấy bình luận',
		'no_comments_in_x' => 'Không có bình luận trong ^',
		'no_questions_found' => 'Không tìm thấy câu hỏi',
		'no_questions_in_x' => 'Không tìm thấy câu trả lời trong ^',
		'no_related_qs_title' => 'Không tìm thấy câu hỏi liên quan',
		'no_results_for_x' => 'Không tìm thấy cho ^',
		'no_tags_found' => 'Không tìm thấy nhãn',
		'no_una_questions_found' => 'Không có câu hỏi chưa được trả lời nào được tìm thấy',
		'no_una_questions_in_x' => 'Không có câu hỏi chưa được trả lời trong ^',
		'no_unselected_qs_found' => 'Không có câu hỏi nào thiếu câu trả lời hay nhất được tìm thấy',
		'no_unupvoteda_qs_found' => 'Không có câu hỏi nào thiếu câu trả lời có bình chọn được tìm thấy',
		'page_label' => 'Trang:',
		'page_next' => 'kế tiếp',
		'page_not_found' => 'Trang không được tìm thấy',
		'page_prev' => 'trước',
		'popular_tags' => 'Các nhãn phổ biến nhất',
		'questions_tagged_x' => 'Các câu hỏi được gắn nhãn gần đây ^',
		'recategorized' => 'đã chọn lại chủ đề',
		'recent_activity_in_x' => 'Hoạt động gần đây trong ^',
		'recent_activity_title' => 'Hoạt động gần đây',
		'recent_as_in_x' => 'Câu hỏi được trả lời gần đây trong ^',
		'recent_as_title' => 'Câu được trả lời gần đây',
		'recent_cs_in_x' => 'Câu hỏi được bình luận gần đây trong ^',
		'recent_cs_title' => 'Câu hỏi được bình luận trong',
		'recent_qs_as_in_x' => 'Câu hỏi và câu trả lời gần đây trong ^',
		'recent_qs_as_title' => 'Câu hỏi và câu trả lời gần đây',
		'recent_qs_in_x' => 'Câu hỏi gần đây trong ^',
		'recent_qs_title' => 'Câu hỏi gần đây',
		'related_qs_title' => 'Câu hỏi liên quan',
		'remove_favorites' => 'Xóa bỏ mục yêu thích của tôi',
		'remove_x_favorites' => 'Xóa bỏ ^ trong mục yêu thích của tôi',
		'reopened' => 'đã mở lại',
		'reshown' => 'đã hiện lại',
		'results_for_x' => 'Kết quả tìm kiếm cho ^',
		'retagged' => 'đã tag lại',
		'save_button' => 'Lưu thay đổi',
		'search_button' => 'Tìm kiếm',
		'search_explanation' => 'Xin vui lòng nhập từ khóa vào ô tìm kiếm và thử lại.',
		'search_title' => 'Kết quả tìm kiếm',
		'selected' => 'được bình chọn là câu trả lời hay nhất',
		'send_button' => 'Gửi',
		'suggest_ask' => '^1Hãy đặt câu hỏi^2 để được trợ giúp.',
		'suggest_category_qs' => 'Để xem thêm, hãy bấm vào tất cả ^1các câu hỏi trong chủ đề này^2.',
		'suggest_qs_tags' => 'Để xem thêm, hãy bấm vào ^1danh sách đầy đủ các câu hỏi^2 or ^3các nhãn phổ biến^4.',
		'suggest_qs' => 'Để xem thêm, hãy bấm vào ^1danh sách đầy đủ các câu hỏi^2.',
		'unanswered_qs_in_x' => 'Các câu hỏi chưa có câu trả lời trong ^',
		'unanswered_qs_title' => 'Các câu hỏi gần đây chưa có câu trả lời hay nhất',
		'unselected_qs_in_x' => 'Các câu hỏi chưa có câu trả lời được bình chọn trong ^',
		'unselected_qs_title' => 'Các câu hỏi gần đây chưa có câu trả lời hay nhất',
		'unupvoteda_qs_in_x' => 'Các câu hỏi chưa có câu trả lời được bình chọn trong ^',
		'unupvoteda_qs_title' => 'Các câu hỏi gần đây có câu trả lời chưa được bình chọn',
		'upload_limit' => 'Tải lên quá nhiều - xin vui lòng thử lại sau 1 tiếng nữa',
		'view_q_must_be_approved' => 'Tài khoản của bạn phải được phê duyệt để xem các trang câu hỏi.',
		'view_q_must_confirm' => 'Xin vui lòng ^5xác nhận địa chỉ thư điện tử^6 để xem các trang câu hỏi.',
		'view_q_must_login' => 'Xin vui lòng ^1đăng nhập^2 hoặc ^3đăng ký thành viên^4 để xem các trang câu hỏi.',
		'viewed_qs_in_x' => 'Câu hỏi được xem nhiều nhất trong ^',
		'viewed_qs_title' => 'Câu hỏi được xem nhiều nhất',
		'vote_disabled_approve' => 'Tài khoản của bạn phải được phê duyệt trước khi bạn có thể bình chọn',
		'vote_disabled_down' => 'Rút lại bình chọn chỉ có thể cho một vài thành viên',
		'vote_disabled_down_approve' => 'Tài khoản của bạn phải được phê duyệt trước khi hủy bỏ bình chọn',
		'vote_disabled_hidden_a' => 'Bạn không thể bình chọn cho câu trả lời bị ẩn',
		'vote_disabled_hidden_q' => 'Bạn không thể bình chọn cho câu hỏi bị ẩn',
		'vote_disabled_level' => 'Bình chọn chỉ có thể cho một vài thành viên',
		'vote_disabled_my_a' => 'Bạn không thể bình chọn cho câu trả lời của bạn',
		'vote_disabled_my_q' => 'Bạn không thể bình chọn cho câu hỏi của bạn',
		'vote_disabled_q_page_only' => 'Xin vui lòng xem câu hỏi này để bình chọn',
		'vote_down_must_confirm' => 'Xin vui lòng ^5xác nhận thư báo^6 để rút lại bình chọn.',
		'vote_down_popup' => 'Bấm để không thích điều này',
		'vote_limit' => 'Được nhận quá nhiều bình chọn - xin vui lòng thử lại sau 1 tiếng nữa',
		'vote_must_confirm' => 'Xin vui lòng ^5xác nhận địa chỉ thư báo^6 để bình chọn.',
		'vote_must_login' => 'Xin vui lòng ^1đăng nhập^2 hoặc ^3đăng ký thành viên^4 để bình chọn.',
		'vote_not_allowed' => 'Không được phép bình chọn',
		'vote_up_popup' => 'Bấm để bình chọn',
		'voted_down_popup' => 'Bạn đã không thích điều này - bấm để bình chọn lại',
		'voted_qs_in_x' => 'Các câu hỏi có lượt bình chọn cao nhất trong ^',
		'voted_qs_title' => 'Các câu hỏi có lượt bình chọn cao nhất',
		'voted_up_popup' => 'Bạn đã bình chọn - bấm để rút lại bình chọn',
		'written' => '', // blank in English - placeholder for other languages
		'x_ago' => '^ trước đây',
		'x_answers' => '^ Câu trả lời',
		'x_comments' => '^ Bình luận',
		'x_days' => '^ ngày',
		'x_disliked' => '^ không thích',
		'x_flags' => '^ phản ánh',
		'x_hours' => '^ giờ',
		'x_liked' => '^ thích',
		'x_minutes' => '^ phút',
		'x_months' => '^ tháng',
		'x_points' => '^ điểm',
		'x_questions' => '^ Câu hỏi',
		'x_seconds' => '^ giây',
		'x_tags' => '^ Nhãn',
		'x_users' => '^ Thành viên',
		'x_views' => '^ Lượt xem',
		'x_votes' => '^ Phiếu',
		'x_weeks' => '^ tuần',
		'x_years' => '^ năm',
	);
	

/*
	Omit PHP closing tag to help avoid accidental output
*/